# Setup
title: Iris 的博客
description: 简单的学习记录
url: https://iriswang1995.github.io/
avatar: /头像.jpg
paginate: 5
permalink: pretty
cover_image: /背景.gif

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: 
  card: 
logo: 
social:
  name: 
  links:
    - 
    - 
google_site_verification: 
lang: 

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx
